### ISSUE TITLE
Java syntax editor throws IOException in Java 8 parsing the Interface 'Iterable'

### ISSUE THREAD

**Issue by stevenupton** [bobbylight/RSyntaxTextArea#122]
The Iterable interface in Java 8 adds 2 new methods: 

<code>
default void forEach(Consumer<? super T> action) {
        Objects.requireNonNull(action);
        for (T t : this) {
            action.accept(t);
        }
    }
</code>

and 
<code>
default Spliterator<T> spliterator() {
        return Spliterators.spliteratorUnknownSize(iterator(), 0);
    }
</code>

The <b>default</b> keyword is not parsed correctly in ASTFactory and following exception is thrown:

<code>
java.io.IOException: Expected identifier, found: [TokenImpl: type=65548; lexeme="default"; line=71; col=4; offs=1637; invalid=false]
	at org.fife.rsta.ac.java.rjc.parser.ASTFactory._getType(ASTFactory.java:1292)
	at org.fife.rsta.ac.java.rjc.parser.ASTFactory._getType(ASTFactory.java:1235)
	at org.fife.rsta.ac.java.rjc.parser.ASTFactory._getInterfaceMemberDecl(ASTFactory.java:840)
	at org.fife.rsta.ac.java.rjc.parser.ASTFactory._getInterfaceBody(ASTFactory.java:741)
	at org.fife.rsta.ac.java.rjc.parser.ASTFactory._getNormalInterfaceDeclaration(ASTFactory.java:1179)
	at org.fife.rsta.ac.java.rjc.parser.ASTFactory._getClassOrInterfaceDeclaration(ASTFactory.java:453)
	at org.fife.rsta.ac.java.rjc.parser.ASTFactory._getTypeDeclaration(ASTFactory.java:1407)
	at org.fife.rsta.ac.java.rjc.parser.ASTFactory.getCompilationUnit(ASTFactory.java:590)
	at org.fife.rsta.ac.java.buildpath.ZipSourceLocation.getCompilationUnit(ZipSourceLocation.java:84)
	at org.fife.rsta.ac.java.Util.getCompilationUnitFromDisk(Util.java:583)
	at org.fife.rsta.ac.java.MethodInfoData.getMethodFromSourceLoc(MethodInfoData.java:117)
	at org.fife.rsta.ac.java.MethodInfoData.getSummaryFromSourceLoc(MethodInfoData.java:327)
	at org.fife.rsta.ac.java.MethodInfoData.getSummary(MethodInfoData.java:304)
	at org.fife.rsta.ac.java.MethodInfoData.getParameterName(MethodInfoData.java:221)
	at org.fife.rsta.ac.java.MethodCompletion.<init>(MethodCompletion.java:111)
</code>

**Comment by stevenupton** [comment]
Java 8 support needs implementing. The ConstantPoolInfoFactory throws IO exception reading String class.

**Comment by bobbylight** [comment]
See [Pull Request #23](https://github.com/bobbylight/RSTALanguageSupport/pull/23) in the RSTALanguageSupport project.  This should address most (all?) of this issue.

**Comment by bobbylight** [comment]
[Pull Request #23](https://github.com/bobbylight/RSTALanguageSupport/pull/23) in the RSTALanguageSupport project has been merged, so I'm closing this ticket.
