### ISSUE TITLE
NPE on getMatchingBracketPosition

### ISSUE THREAD

**Issue by samczsun** [bobbylight/RSyntaxTextArea#165]
```
java.lang.NullPointerException
	at org.fife.ui.rsyntaxtextarea.RSyntaxUtilities.getMatchingBracketPosition(RSyntaxUtilities.java:462)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.doBracketMatching(RSyntaxTextArea.java:766)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.fireCaretUpdate(RSyntaxTextArea.java:812)
	at javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4394)
	at javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4416)
	at javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:802)
	at javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1274)
	at javax.swing.text.DefaultCaret.handleMoveDot(DefaultCaret.java:1101)
	at javax.swing.text.DefaultCaret$DefaultFilterBypass.moveDot(DefaultCaret.java:1917)
	at javax.swing.text.NavigationFilter.moveDot(NavigationFilter.java:79)
	at org.fife.ui.rtextarea.ConfigurableCaret$FoldAwareNavigationFilter.moveDot(ConfigurableCaret.java:676)
	at javax.swing.text.DefaultCaret.moveDot(DefaultCaret.java:1092)
	at javax.swing.text.DefaultCaret.moveDot(DefaultCaret.java:1063)
	at javax.swing.text.JTextComponent.moveCaretPosition(JTextComponent.java:1502)
	at javax.swing.text.JTextComponent.select(JTextComponent.java:1874)
	at javax.swing.text.JTextComponent.setSelectionEnd(JTextComponent.java:1825)
	at org.fife.ui.rsyntaxtextarea.RSyntaxUtilities.selectAndPossiblyCenter(RSyntaxUtilities.java:1370)
	at org.fife.ui.rtextarea.SearchEngine.find(SearchEngine.java:114)
	at com.samczsun.helios.gui.ClassManager.search(ClassManager.java:341)
	at com.samczsun.helios.gui.SearchPopup$3.keyReleased(SearchPopup.java:73)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Unknown Source)
	at org.eclipse.swt.widgets.Text.sendKeyEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.wmKeyUp(Unknown Source)
	at org.eclipse.swt.widgets.Control.WM_KEYUP(Unknown Source)
	at org.eclipse.swt.widgets.Control.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Text.windowProc(Unknown Source)
	at org.eclipse.swt.widgets.Display.windowProc(Unknown Source)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at com.samczsun.helios.bootloader.DisplayPumper.run(DisplayPumper.java:41)
	at java.lang.Thread.run(Thread.java:745)
```

It may be SWT interfering but I thought I'd ask just in case you knew what might be going on

**Comment by bobbylight** [comment]
Looks like this is because you aren't running Swing operations on the EDT (they're running on the SWT event loop thread).  Try wrapping your call to `SearchEngine.find()` in `SwingUtilities.invokeLater()`.

**Comment by mrerrormessage** [comment]
I'm running into this as well, and in my case it's definitely invoked on the Swing thread. I am using a custom `TokenMaker` though, so perhaps I'm doing something wrong? I only see this when I'm matching brackets across multiple lines (for instance `abc [ 123 ]` is fine, but `abc [ \n 123 ]` raises the error below).

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at org.fife.ui.rsyntaxtextarea.RSyntaxUtilities.getMatchingBracketPosition(RSyntaxUtilities.java:478)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.doBracketMatching(RSyntaxTextArea.java:778)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.fireCaretUpdate(RSyntaxTextArea.java:839)
        at javax.swing.text.JTextComponent$MutableCaretEvent.fire(JTextComponent.java:4394)
        at javax.swing.text.JTextComponent$MutableCaretEvent.stateChanged(JTextComponent.java:4416)
        at javax.swing.text.DefaultCaret.fireStateChanged(DefaultCaret.java:802)
        at javax.swing.text.DefaultCaret.changeCaretPosition(DefaultCaret.java:1274)
        at javax.swing.text.DefaultCaret.handleSetDot(DefaultCaret.java:1173)
        at javax.swing.text.DefaultCaret$DefaultFilterBypass.setDot(DefaultCaret.java:1913)
        at javax.swing.text.NavigationFilter.setDot(NavigationFilter.java:64)
        at org.fife.ui.rtextarea.ConfigurableCaret$FoldAwareNavigationFilter.setDot(ConfigurableCaret.java:724)
        at javax.swing.text.DefaultCaret.setDot(DefaultCaret.java:1151)
        at javax.swing.text.DefaultCaret$Handler.insertUpdate(DefaultCaret.java:1723)
        at javax.swing.text.AbstractDocument.fireInsertUpdate(AbstractDocument.java:201)
        at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.fireInsertUpdate(RSyntaxDocument.java:187)
        at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:748)
        at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
        at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
        at javax.swing.text.AbstractDocument.replace(AbstractDocument.java:669)
        at javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1328)
        at org.fife.ui.rtextarea.RTextArea.handleReplaceSelection(RTextArea.java:870)
        at org.fife.ui.rtextarea.RTextArea.replaceSelection(RTextArea.java:1235)
        at javax.swing.text.DefaultEditorKit$DefaultKeyTypedAction.actionPerformed(DefaultEditorKit.java:884)
        at org.fife.ui.rtextarea.RTextAreaEditorKit$DefaultKeyTypedAction.actionPerformedImpl(RTextAreaEditorKit.java:862)
        at org.fife.ui.rtextarea.RecordableTextAction.actionPerformed(RecordableTextAction.java:106)
        at javax.swing.SwingUtilities.notifyAction(SwingUtilities.java:1663)
        at javax.swing.JComponent.processKeyBinding(JComponent.java:2882)
        at javax.swing.JComponent.processKeyBindings(JComponent.java:2929)
        at javax.swing.JComponent.processKeyEvent(JComponent.java:2845)
        at java.awt.Component.processEvent(Component.java:6310)
        at java.awt.Container.processEvent(Container.java:2236)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
        at java.awt.Component.dispatchEventImpl(Component.java:4760)
        at java.awt.Container.dispatchEventImpl(Container.java:2294)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I'm happy to add in a null check to RSyntaxUtilities line 478 and open a PR if you consider that the appropriate solution?
