### ISSUE TITLE
NPE in Gutter component when changing its orientation within its UI

### ISSUE THREAD

**Issue by mgarin** [bobbylight/RSyntaxTextArea#188]
Shortly about the case - I'm working on a [custom L&F](https://github.com/mgarin/weblaf) which performs lots of various updates upon component UI initialization. In one of such updates component's `ComponentOrientation` gets updated if the one component currently uses is different from the one provided globally (depending on application language).

Recently I tried our Arabic language to test out RTL (right-to-left) orientation and encountered the next exception within [`Gutter`](https://github.com/bobbylight/RSyntaxTextArea/blob/master/src/main/java/org/fife/ui/rtextarea/Gutter.java) component initialization:
```
java.lang.reflect.InvocationTargetException
	at sun.reflect.GeneratedMethodAccessor26.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.alee.utils.ReflectUtils.callMethod(ReflectUtils.java:1208)
	at com.alee.managers.style.data.ComponentStyle.setFieldValue(ComponentStyle.java:531)
	at com.alee.managers.style.data.ComponentStyle.installPainter(ComponentStyle.java:421)
	at com.alee.managers.style.data.ComponentStyle.apply(ComponentStyle.java:362)
	at com.alee.managers.style.AbstractSkin.applySkin(AbstractSkin.java:65)
	at com.alee.managers.style.StyleData.applySkin(StyleData.java:264)
	at com.alee.managers.style.StyleManager.installSkin(StyleManager.java:437)
	at com.alee.laf.panel.WebPanelUI.installUI(WebPanelUI.java:80)
	at javax.swing.JComponent.setUI(JComponent.java:662)
	at javax.swing.JPanel.setUI(JPanel.java:136)
	at javax.swing.JPanel.updateUI(JPanel.java:109)
	at javax.swing.JPanel.<init>(JPanel.java:69)
	at javax.swing.JPanel.<init>(JPanel.java:92)
	at javax.swing.JPanel.<init>(JPanel.java:100)
	at org.fife.ui.rtextarea.Gutter.<init>(Gutter.java:128)
	at org.fife.ui.rtextarea.RTextScrollPane.<init>(RTextScrollPane.java:133)
	at org.fife.ui.rtextarea.RTextScrollPane.<init>(RTextScrollPane.java:90)
	at org.fife.ui.rtextarea.RTextScrollPane.<init>(RTextScrollPane.java:60)
	at com.alee.extended.syntax.WebSyntaxScrollPane.<init>(WebSyntaxScrollPane.java:108)
	at com.alee.extended.syntax.WebSyntaxArea.createScroll(WebSyntaxArea.java:212)
	at com.alee.extended.syntax.WebSyntaxArea.createScroll(WebSyntaxArea.java:200)
	at com.alee.extended.syntax.WebSyntaxArea.main(WebSyntaxArea.java:407)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.lang.NullPointerException
	at org.fife.ui.rtextarea.Gutter.setComponentOrientation(Gutter.java:560)
	at com.alee.utils.SwingUtils.setOrientation(SwingUtils.java:624)
	at com.alee.utils.SwingUtils.setOrientation(SwingUtils.java:610)
	at com.alee.painter.AbstractPainter.updateOrientation(AbstractPainter.java:246)
	at com.alee.painter.AbstractPainter.install(AbstractPainter.java:89)
	at com.alee.painter.decoration.AbstractDecorationPainter.install(AbstractDecorationPainter.java:85)
	at com.alee.painter.PainterSupport.installPainter(PainterSupport.java:137)
	at com.alee.painter.PainterSupport.setPainter(PainterSupport.java:106)
	at com.alee.laf.panel.WebPanelUI.setPainter(WebPanelUI.java:151)
	... 30 more
```
Some part of this exception is not really interesting for you as it contains L&F -related classes, pretty much all up to the final NPE - `Gutter.setComponentOrientation(Gutter.java:560)`.

So I have investigated that exception here is why it happens - `Gutter` tries to adjust its existing border in `setComponentOrientation` method according to new orientation. But border might not exist at this point which is not being checked.

Usually it would exist because it is actually initialized within the `Gutter` constructor:
```java
setBorder(new GutterBorder(0, 0, 0, 1)); // Assume ltr
```
But `Gutter` extends `JPanel` and because of that uses a panel UI provided by my custom L&F which in its turn changes its orientation deep within the UI install method. At that point `Gutter` constructor is not yet fully excecuted and its border is simply `null`.

I would suggest changing this method in `Gutter`:
```java
	@Override
	public void setComponentOrientation(ComponentOrientation o) {
		// Reuse the border to preserve its color.
		if (o.isLeftToRight()) {
			((GutterBorder)getBorder()).setEdges(0, 0, 0, 1);
		}
		else {
			((GutterBorder)getBorder()).setEdges(0, 1, 0, 0);
		}
		super.setComponentOrientation(o);
	}
```
To something more safe like this:
```java
    @Override
    public void setComponentOrientation ( ComponentOrientation o )
    {
        // Reuse the border to preserve its color.
        if ( getBorder () != null && getBorder () instanceof GutterBorder )
        {
            if ( o.isLeftToRight () )
            {
                ( ( GutterBorder ) getBorder () ).setEdges ( 0, 0, 0, 1 );
            }
            else
            {
                ( ( GutterBorder ) getBorder () ).setEdges ( 0, 1, 0, 0 );
            }
        }
        super.setComponentOrientation ( o );
    }
```
Since border might be `null` or even have a different type at this point, depending on the UI.

---

There could also be a different approach to fix this - you might change the `Gutter` to extend `JComponent` instead of `JPanel` - in that case it will not have any UI by default and will simply be an empty canvas/container which seems to be perfect for its purpose.

This way you will ensure that some custom UI won't break your specific border and other possible component settings.

**Comment by mgarin** [comment]
Just noticed that you actually have this method overridden:
```java
@Override
public void setBorder(Border border) {
	if (border instanceof GutterBorder) {
		super.setBorder(border);
	}
}
```
Which means there is no need to check border type, but NPE might still occur when border is being referenced early on (from the UI).

**Comment by bobbylight** [comment]
Fixed, thanks for this.  I went with the null/instanceof check in setComponentOrientation because it's explicit what we're checking for when reading the code, and I had issues when extending JComponent in the past (can't remember what, surely my own misunderstandings of Swing vs. actual issues, but I'm sticking with what works for now.  :))

Also, please ignore the build failures on Travis CI - I've adopted the use of checkstyle and it's forcing my hand to migrate from building with Java 5 to Java 6, but I haven't had time to fix that yet.
