### ISSUE TITLE
Theme problem

### ISSUE THREAD

**Issue by DevilLordAero** [bobbylight/RSyntaxTextArea#190]
When i compile my java code to runnable jar, the theme cannot be applied, but when in eclipse, it can be applied fine..

```java
private void eclipseTheme() {
	      try {
	    	  Theme theme = Theme.load(getClass().getResourceAsStream(new FileInputStream(new File("/themes/eclipse.xml")).toString()));
	          theme.apply(textArea);
	      } catch (IOException ioe) { // Never happens
	         ioe.printStackTrace();
	      }
	}
```

**Comment by bobbylight** [comment]
Please ensure your theme XML file is accessible in the location you specify in your code.  By using the File constructor as you are, Java looks for a literal flat file named `/themes/eclipse.xml`.    You probably want to use `Class.getResourceAsStream()`, like is shown in [this example](https://github.com/bobbylight/RSyntaxTextArea/wiki/Example:-Setting-the-theme).

**Comment by DevilLordAero** [comment]
thx

**Comment by Haeri** [comment]
For some reason the Theme.load function throws an exception that I can't catch. I have 2 directories where I look. If the xml file is not in the first one, then I look in the second one. I use two try catch statements for this, but I still get an exception error when looking for a non existing file.
```
try {
    String _path = DIR_THEMES + themeName + ".xml";
    theme = Theme.load(getClass().getResourceAsStream(_path));
} catch (Exception e1) {
    s1 = false;
}
```
Any idea why this is happening? (It actually works but it throws an exception that I can't prevent)

```
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at org.fife.ui.rsyntaxtextarea.Theme$XmlHandler.load(Theme.java:616)
	at org.fife.ui.rsyntaxtextarea.Theme.load(Theme.java:351)
	at org.fife.ui.rsyntaxtextarea.Theme.load(Theme.java:329)
...
```

PS: Thank you so much for this repo! It was so easy to merge with my project and it does exactly what I needed :D

**Comment by bobbylight** [comment]
No, a catch of all java.lang.Exceptions should catch an IOException.  Can you provide a short, single-file demo application that shows this problem?

**Comment by Haeri** [comment]
Ok I have now tried it with the [example script](https://github.com/bobbylight/RSyntaxTextArea/wiki/Example:-Setting-the-theme) And just deleted the ` ioe.printStackTrace();` part, so I don't get the exception print. Still the same problem.

Could it be a problem that I am using `rsyntaxtextarea-2.6.0.jar` from the SNAPSHOT folder?

**Comment by bobbylight** [comment]
Looks like that example has a typo; the XML resource is "eclilpse.xml", not "eclipse_theme.xml".  Is that your problem?  If not, please post the exception you get when running the demo application.

For reference, the available themes are here:

https://github.com/bobbylight/RSyntaxTextArea/tree/master/src/main/resources/org/fife/ui/rsyntaxtextarea/themes

**Comment by Haeri** [comment]
Ok here is the slightly modified Demo code

```
package MainPackage;
import java.awt.BorderLayout;
import java.io.IOException;

import javax.swing.*;

import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.fife.ui.rsyntaxtextarea.SyntaxConstants;
import org.fife.ui.rsyntaxtextarea.Theme;
import org.fife.ui.rtextarea.RTextScrollPane;


/**
 * A simple example showing how to use RSyntaxTextArea to add Java syntax
 * highlighting to a Swing application.<p>
 * 
 * This example uses RSyntaxTextArea 2.5.6.
 */
public class TextEditorDemo extends JFrame {

   public TextEditorDemo() {

      JPanel cp = new JPanel(new BorderLayout());

      RSyntaxTextArea textArea = new RSyntaxTextArea(20, 60);
      textArea.setSyntaxEditingStyle(SyntaxConstants.SYNTAX_STYLE_JAVA);
      textArea.setCodeFoldingEnabled(true);
      RTextScrollPane sp = new RTextScrollPane(textArea);
      cp.add(sp);

      try {
         Theme theme = Theme.load(getClass().getResourceAsStream(
               "/Resources/themes/NotExisting.xml"));
         theme.apply(textArea);
      } catch (IOException ioe) {
    	  // It is ok to fail, but don't gie me an exception
         System.out.println("Dont print trace pls");
      }

      setContentPane(cp);
      setTitle("Text Editor Demo");
      setDefaultCloseOperation(EXIT_ON_CLOSE);
      pack();
      setLocationRelativeTo(null);

   }

   public static void main(String[] args) {
      // Start all Swing applications on the EDT.
      SwingUtilities.invokeLater(new Runnable() {
         public void run() {
            new TextEditorDemo().setVisible(true);
         }
      });
   }

}
```

and here is the stack trace:
```
java.io.IOException: Stream closed
	at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(XMLEntityManager.java:2876)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(XMLEntityManager.java:702)
	at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(XMLVersionDetector.java:189)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:812)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:649)
	at org.fife.ui.rsyntaxtextarea.Theme$XmlHandler.load(Theme.java:616)
	at org.fife.ui.rsyntaxtextarea.Theme.load(Theme.java:351)
	at org.fife.ui.rsyntaxtextarea.Theme.load(Theme.java:329)
	at MainPackage.TextEditorDemo.<init>(TextEditorDemo.java:32)
	at MainPackage.TextEditorDemo$1.run(TextEditorDemo.java:52)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Everything is actually working, but I just don't like, that I get a stack trace thrown in the console.
