### ISSUE TITLE
problem while testing RSyntaxTextArea

### ISSUE THREAD

**Issue by mbrebion** [bobbylight/RSyntaxTextArea#333]
I've tried to use your hello world test code (Java 8 ; via netbeans) and I get the following error : 
`
Exception in thread "AWT-EventQueue-0" java.lang.ExceptionInInitializerError
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaUI.<clinit>(RSyntaxTextAreaUI.java:43)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.createRTextAreaUI(RSyntaxTextArea.java:756)
	at org.fife.ui.rtextarea.RTextAreaBase.init(RTextAreaBase.java:656)
	at org.fife.ui.rtextarea.RTextArea.init(RTextArea.java:876)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.init(RSyntaxTextArea.java:1939)
	at org.fife.ui.rtextarea.RTextAreaBase.<init>(RTextAreaBase.java:119)
	at org.fife.ui.rtextarea.RTextArea.<init>(RTextArea.java:224)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.<init>(RSyntaxTextArea.java:389)
	at texteditor.TextEditor.<init>(TextEditor.java:19)
	at texteditor.TextEditor.lambda$main$0(TextEditor.java:36)
`
This happens during instanciation of the RSyntaxTextArea
What should I do ?

I've read elsewhere that I should include the jar file and not the sources. 
However, when I build the project with the provided command, I have no idea of where the appropriate jar file is.

Cordially
Maxence Miguel-Brebion

**Comment by bobbylight** [comment]
Is there more of the stack trace that you cut off?

How are you importing the project into NetBeans?  My guess is that you are not adding the `src/main/resources` folder to the build path.  Being a gradle project, most IDE's will recognize the project's structure and set things up properly, but depending on how you're adding RSTA to your project that may not be happening.

Do you get this error if you clone this repository through your IDE (either by pointing to the URL if that's possible, it is in IntelliJ for example, or by cloning it and opening it via its `build.gradle` in your IDE?

**Comment by mbrebion** [comment]
Ok, 
cloning the project directly into Netbeans fixed the problem.
Thank you for this very astonishing project !
I'd been trying to write a small IDE for latex code but ending with big headaches when dealing with line breaking...

**Comment by bobbylight** [comment]
Excellent, glad you're up and running!
