### ISSUE TITLE
HeadlessException when creating RSyntaxTextArea

### ISSUE THREAD

**Issue by vlsi** [bobbylight/RSyntaxTextArea#336]
Could you please wrap `getMenuShortcutKeyMask` with `catch(HeadlessException)`, so `RSyntaxTextArea` works in headless mode as well?

There's a sane default implementation: return `META_MASK` for `macOS` and `CTRL_MASK` otherwise.

```
java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
    at java.desktop/sun.awt.HeadlessToolkit.getMenuShortcutKeyMask(HeadlessToolkit.java:135)
    at org.fife.ui.rtextarea.RTADefaultInputMap.getDefaultModifier(RTADefaultInputMap.java:158)
    at org.fife.ui.rtextarea.RTADefaultInputMap.<init>(RTADefaultInputMap.java:53)
    at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaDefaultInputMap.<init>(RSyntaxTextAreaDefaultInputMap.java:37)
    at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaUI.getRTextAreaInputMap(RSyntaxTextAreaUI.java:134)
    at org.fife.ui.rtextarea.RTextAreaUI.installKeyboardActions(RTextAreaUI.java:403)
    at java.desktop/javax.swing.plaf.basic.BasicTextUI.installUI(BasicTextUI.java:841)
    at org.fife.ui.rtextarea.RTextAreaUI.installUI(RTextAreaUI.java:424)
    at java.desktop/javax.swing.JComponent.setUI(JComponent.java:685)
    at java.desktop/javax.swing.text.JTextComponent.setUI(JTextComponent.java:342)
    at org.fife.ui.rtextarea.RTextAreaBase.setRTextAreaUI(RTextAreaBase.java:1130)
    at org.fife.ui.rtextarea.RTextAreaBase.init(RTextAreaBase.java:656)
    at org.fife.ui.rtextarea.RTextArea.init(RTextArea.java:876)
    at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.init(RSyntaxTextArea.java:1988)
    at org.fife.ui.rtextarea.RTextAreaBase.<init>(RTextAreaBase.java:119)
    at org.fife.ui.rtextarea.RTextArea.<init>(RTextArea.java:224)
    at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.<init>(RSyntaxTextArea.java:384)

```

**Comment by bobbylight** [comment]
Thanks for this!  Our CI builds stub out an X11 environment so I didn't run into this, but I agree it's a good idea.
