### ISSUE TITLE
JFlex fails

### ISSUE THREAD

**Issue by manticore-projects** [bobbylight/RSyntaxTextArea#378]
Greetings Bobby,

currently the SQL mode does not recognize the `MERGE` statement or the `CASE` expression.
So i forked the latest 3.1.3 Snapshot, edited the `SQLTokenMaker.flex`, ran it through `JFlex-1.8.2`, removed the 2 redundant methods `zzRefill()` and `yyreset(java.io.Reader reader)` and reverted 

```java
zzCurrentPos = zzMarkedPos = zzPushbackPos = s.offset;
```

back to
```java
zzCurrentPos = zzMarkedPos = s.offset;
```

Valid Java code, which compiled. Deployed it to my local Maven in order to try it and then all hell broke lose:
```sh
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException
	at java.base/java.lang.Character.codePointAt(Character.java:8327)
	at org.fife.ui.rsyntaxtextarea.modes.SQLTokenMaker.yylex(SQLTokenMaker.java:1251)
	at org.fife.ui.rsyntaxtextarea.modes.SQLTokenMaker.getTokenList(SQLTokenMaker.java:979)
	at org.fife.ui.rsyntaxtextarea.TokenMakerBase.getLastTokenTypeOnLine(TokenMakerBase.java:216)
	at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.updateLastTokensBelow(RSyntaxDocument.java:608)
	at org.fife.ui.rsyntaxtextarea.RSyntaxDocument.fireInsertUpdate(RSyntaxDocument.java:182)
	at java.desktop/javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:757)
	at java.desktop/javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:716)
	at java.desktop/javax.swing.text.PlainDocument.insertString(PlainDocument.java:131)
	at java.desktop/javax.swing.text.AbstractDocument.replace(AbstractDocument.java:675)
	at java.desktop/javax.swing.text.JTextComponent.replaceSelection(JTextComponent.java:1339)
	at org.fife.ui.rtextarea.RTextArea.handleReplaceSelection(RTextArea.java:887)
	at org.fife.ui.rtextarea.RTextArea.replaceSelection(RTextArea.java:1261)
```

What did I do wrong?
I also noticed, that the newly generated SQLTokenMaker.flex has many more differences then I would have expected? Is the procedure still valid? Should I try a previous version of JFlex (if so, which one please)?

Thank you already and cheers!

[SQLTokenMaker.zip](https://github.com/bobbylight/RSyntaxTextArea/files/6403260/SQLTokenMaker.zip)

**Comment by manticore-projects** [comment]
I got it working with JFlex 1.5.1 and the `MERGE` statements and `CASE` expressions will be highlighted now:

![image](https://user-images.githubusercontent.com/18080123/116657269-57614080-a9b8-11eb-9cd5-d7b703b7c20e.png)
