### ISSUE TITLE
NoSuchMethodError with escapeForHtml

### ISSUE THREAD

**Issue by idiatech** [bobbylight/RSyntaxTextArea#418]
Hello,

When I do Ctrl+Space and there is only one possibility, this error appears:

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: org.fife.ui.rsyntaxtextarea.RSyntaxUtilities.escapeForHtml(Ljava/lang/String;Ljava/lang/String;Z)Ljava/lang/String;
	at org.fife.ui.autocomplete.ParameterizedCompletionDescriptionToolTip.updateText(ParameterizedCompletionDescriptionToolTip.java:201)
	at org.fife.ui.autocomplete.ParameterizedCompletionDescriptionToolTip.<init>(ParameterizedCompletionDescriptionToolTip.java:95)
	at org.fife.ui.autocomplete.ParameterizedCompletionContext.activate(ParameterizedCompletionContext.java:204)
	at org.fife.ui.autocomplete.AutoCompletion.startParameterizedCompletionAssistance(AutoCompletion.java:1219)
	at org.fife.ui.autocomplete.AutoCompletion.insertCompletion(AutoCompletion.java:642)
	at org.fife.ui.autocomplete.AutoCompletion.insertCompletion(AutoCompletion.java:609)
	at org.fife.ui.autocomplete.AutoCompletion.lambda$refreshPopupWindow$1(AutoCompletion.java:881)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

Thank you

**Comment by bobbylight** [comment]
What versions of RSyntaxTextArea and AutoComplete are you using?  It looks like you have a version mismatch.  In the most recent release some API's changed (duplicated API's between `RSyntaxUtilities` and `HtmlUtil` were consolidated, and it looks like you're using an older version of AutoComplete with a newer version of RSyntaxTextArea.  Can you update RSTA and AutoComplete to 3.1.4/3.1.3 respectively and try again?

As an aside - this change didn't follow semantic versioning, so apologies for that.  I've been largely ignoring semantic versioning with RSTA and its sister projects.  I'm trying to do better moving forward, saving API changes for a future `4.0.0` release for example.

**Comment by idiatech** [comment]
that is the problem, thank you. Solved with the last version
