### ISSUE TITLE
HeadlessException when instantiating RSyntaxTextArea in headless mode

### ISSUE THREAD

**Issue by vlsi** [bobbylight/RSyntaxTextArea#424]
**Description**

Basic features of `RSyntaxTextArea` should work with `-Djava.awt.headless=true` mode.

It would be fine if certain features were not supported (e.g. certain methods might throw `HeadlessException`), however, it is inconvenient when even instantiating RSTA fails in headless mode.

**Steps to Reproduce**
Specific steps to reproduce the behavior:

```java
import org.fife.ui.rsyntaxtextarea.RSyntaxTextArea;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class RSyntaxTextAreaTest {
    @Test
    public void getTextWorks() {
        JTextArea textArea = new RSyntaxTextArea();
        textArea.setText("test");
        Assertions.assertEquals("test", textArea.getText());
    }
```

**Expected behavior**

Test should work just like with `JTextArea`

**Actual behavior**

```
java.awt.HeadlessException
	at java.desktop/javax.swing.text.JTextComponent.checkDragEnabled(JTextComponent.java:698)
	at java.desktop/javax.swing.text.JTextComponent.setDragEnabled(JTextComponent.java:692)
	at org.fife.ui.rtextarea.RTextArea.init(RTextArea.java:918)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.init(RSyntaxTextArea.java:1989)
	at org.fife.ui.rtextarea.RTextAreaBase.<init>(RTextAreaBase.java:82)
	at org.fife.ui.rtextarea.RTextArea.<init>(RTextArea.java:188)
	at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.<init>(RSyntaxTextArea.java:352)
```

Historically, `JMeter` had its own `RSyntaxTextArea` subclass, however, now I incline it is worth to just support headless mode in `RSyntaxTextArea` rather than implementing workarounds in all the used applications.

**Java version**

Liberica JDK 11.0.13

**Additional context**

`java.awt.headless` is an important case for Kotlin Script.
It impacts JMeter users.

See https://github.com/apache/jmeter/pull/696#discussion_r793040752

**Comment by bobbylight** [comment]
@vlsi let me know what else is needed, or if this is sufficient.  I'm not super knowledgable about API's that could cause issues here and run all RSTA's unit tests via xvfb.

**Comment by vlsi** [comment]
@bobbylight , the headless case is running RSTA **without** `xvfb`.

The way to test is to pass `-Djava.awt.headless=true` to the test jvm.
For instance:

`RSyntaxTextArea/RSyntaxTextArea/build.gradle`

```groovy
test {
    testLogging {
        events 'failed' //, 'passed', 'skipped', 'standardOut', 'standardError'

        showExceptions true
        exceptionFormat 'full'
        showCauses true
        showStackTraces true

        showStandardStreams = false
        systemProperty('java.awt.headless', 'true') // <-- pass headless=true to the test JVM
    }
}
```

It yields the following:

```
> Task :RSyntaxTextArea:test

ErrorStripTest > testGetToolTipText() FAILED
    org.opentest4j.AssertionFailedError: expected: <Line: 1> but was: <Строка: 1>
        at app//org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at app//org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at app//org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at app//org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1141)
        at app//org.fife.ui.rsyntaxtextarea.ErrorStripTest.testGetToolTipText(ErrorStripTest.java:106)

RSyntaxTextAreaEditorKitCopyAsStyledTextActionTest > testActionPerformedImpl_copyAsStyledText() FAILED
    java.awt.HeadlessException
        at java.desktop/sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:122)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.reset(RtfGenerator.java:493)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.<init>(RtfGenerator.java:82)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getTextAsRtf(RSyntaxTextArea.java:1749)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:666)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:633)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaEditorKit$CopyCutAsStyledTextAction.actionPerformedImpl(RSyntaxTextAreaEditorKit.java:667)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaEditorKitCopyAsStyledTextActionTest.testActionPerformedImpl_copyAsStyledText(RSyntaxTextAreaEditorKitCopyAsStyledTextActionTest.java:44)

RSyntaxTextAreaEditorKitCopyAsStyledTextActionTest > test_disabledStyledCopyCutAction() FAILED
    java.awt.HeadlessException
        at java.desktop/sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:122)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.reset(RtfGenerator.java:493)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.<init>(RtfGenerator.java:82)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getTextAsRtf(RSyntaxTextArea.java:1749)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:666)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:633)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaEditorKit$CopyCutAsStyledTextAction.actionPerformedImpl(RSyntaxTextAreaEditorKit.java:667)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaEditorKitCopyAsStyledTextActionTest.test_disabledStyledCopyCutAction(RSyntaxTextAreaEditorKitCopyAsStyledTextActionTest.java:104)

RSyntaxTextAreaEditorKitCopyAsStyledTextActionTest > testActionPerformedImpl_cutAsStyledText() FAILED
    java.awt.HeadlessException
        at java.desktop/sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:122)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.reset(RtfGenerator.java:493)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.<init>(RtfGenerator.java:82)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getTextAsRtf(RSyntaxTextArea.java:1749)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:666)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:633)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaEditorKit$CopyCutAsStyledTextAction.actionPerformedImpl(RSyntaxTextAreaEditorKit.java:667)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaEditorKitCopyAsStyledTextActionTest.testActionPerformedImpl_cutAsStyledText(RSyntaxTextAreaEditorKitCopyAsStyledTextActionTest.java:68)

RSyntaxTextAreaTest > testCopyAsStyledText_zeroArg_string_happyPath() FAILED
    java.awt.HeadlessException
        at java.desktop/sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:122)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.reset(RtfGenerator.java:493)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.<init>(RtfGenerator.java:82)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getTextAsRtf(RSyntaxTextArea.java:1749)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:666)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaTest.testCopyAsStyledText_zeroArg_string_happyPath(RSyntaxTextAreaTest.java:280)

RSyntaxTextAreaTest > testCopyAsStyledText_nullThemeArg_string_happyPath() FAILED
    java.awt.HeadlessException
        at java.desktop/sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:122)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.reset(RtfGenerator.java:493)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.<init>(RtfGenerator.java:82)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getTextAsRtf(RSyntaxTextArea.java:1749)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:666)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:633)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaTest.testCopyAsStyledText_nullThemeArg_string_happyPath(RSyntaxTextAreaTest.java:312)

RSyntaxTextAreaTest > testCopyAsStyledText_zeroArg_html_happyPath() FAILED
    java.awt.HeadlessException
        at java.desktop/sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:122)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.reset(RtfGenerator.java:493)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.<init>(RtfGenerator.java:82)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getTextAsRtf(RSyntaxTextArea.java:1749)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:666)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaTest.testCopyAsStyledText_zeroArg_html_happyPath(RSyntaxTextAreaTest.java:229)

RSyntaxTextAreaTest > testCopyAsStyledText_themeArg_string_happyPath() FAILED
    java.awt.HeadlessException
        at java.desktop/sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:122)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.reset(RtfGenerator.java:493)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.<init>(RtfGenerator.java:82)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.getTextAsRtf(RSyntaxTextArea.java:1749)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:666)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextArea.copyAsStyledText(RSyntaxTextArea.java:641)
        at org.fife.ui.rsyntaxtextarea.RSyntaxTextAreaTest.testCopyAsStyledText_themeArg_string_happyPath(RSyntaxTextAreaTest.java:296)

RtfGeneratorTest > testHappyPath() FAILED
    java.awt.HeadlessException
        at java.desktop/sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:122)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.reset(RtfGenerator.java:493)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.<init>(RtfGenerator.java:82)
        at org.fife.ui.rsyntaxtextarea.RtfGeneratorTest.testHappyPath(RtfGeneratorTest.java:44)

RtfGeneratorTest > testNon7BitAscii() FAILED
    java.awt.HeadlessException
        at java.desktop/sun.awt.HeadlessToolkit.getScreenResolution(HeadlessToolkit.java:122)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.reset(RtfGenerator.java:493)
        at org.fife.ui.rsyntaxtextarea.RtfGenerator.<init>(RtfGenerator.java:82)
        at org.fife.ui.rsyntaxtextarea.RtfGeneratorTest.testNon7BitAscii(RtfGeneratorTest.java:55)

FocusableTipTest > testShowFocusableTip_happyPath() FAILED
    java.awt.HeadlessException
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
        at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
        at java.desktop/javax.swing.JWindow.<init>(JWindow.java:209)
        at org.fife.ui.rsyntaxtextarea.focusabletip.TipWindow.<init>(TipWindow.java:78)
        at org.fife.ui.rsyntaxtextarea.focusabletip.FocusableTip.createAndShowTipWindow(FocusableTip.java:103)
        at org.fife.ui.rsyntaxtextarea.focusabletip.FocusableTip.toolTipRequested(FocusableTip.java:289)
        at org.fife.ui.rsyntaxtextarea.focusabletip.FocusableTipTest.testShowFocusableTip_happyPath(FocusableTipTest.java:65)

ClipboardHistoryPopupTest > testSetContents() FAILED
    java.awt.HeadlessException
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at org.fife.ui.rtextarea.ClipboardHistoryPopupTest.setUp(ClipboardHistoryPopupTest.java:37)

ClipboardHistoryPopupTest > testGetPreferredSize() FAILED
    java.awt.HeadlessException
        at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
        at java.desktop/java.awt.Window.<init>(Window.java:548)
        at java.desktop/java.awt.Frame.<init>(Frame.java:423)
        at java.desktop/java.awt.Frame.<init>(Frame.java:388)
        at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
        at org.fife.ui.rtextarea.ClipboardHistoryPopupTest.setUp(ClipboardHistoryPopupTest.java:37)

RTextAreaEditorKitPasteActionTest > testActionPerformedImpl() FAILED
    java.awt.HeadlessException
        at java.desktop/sun.awt.HeadlessToolkit.getSystemClipboard(HeadlessToolkit.java:216)
        at org.fife.ui.rtextarea.RTextAreaEditorKitPasteActionTest.testActionPerformedImpl(RTextAreaEditorKitPasteActionTest.java:42)

2254 tests completed, 14 failed, 8 skipped

> Task :RSyntaxTextArea:test FAILED
```

I think ClipboardHistoryPopupTest / FocusableTipTest can't work in headless mode, so it would probably make sense to add `assume(!headless)` so the test is skipped in headless mode.

However, `RtfGenerator.reset` could probably be adjusted to use 72 dpi in headless mode.

**Comment by bobbylight** [comment]
Thanks, I'll take a look.  Yeah I'm aware xvfb hides headless issues, which is why I was looking for specifically what issues you were aware of when running headlessly :P  You're right that running all the unit tests headlessly is probably a great way to fish out the obvious issues.
