### ISSUE TITLE
Possible NPE in SyntaxView.calculateLongestLine

### ISSUE THREAD

**Issue by pskowronek** [bobbylight/RSyntaxTextArea#485]
**Description**
Possible NPE in SyntaxView.calculateLongestLine.

**Steps to Reproduce**
Not known yet.

**Expected behavior**
No NPE thrown.

**Actual behavior**
NPE is thrown

**Additional context**

```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "java.awt.Component.getFont()" because "c" is null
        at org.fife.ui.rsyntaxtextarea.SyntaxView.calculateLongestLine(SyntaxView.java:103)
        at org.fife.ui.rsyntaxtextarea.SyntaxView.updateMetrics(SyntaxView.java:904)
        at org.fife.ui.rsyntaxtextarea.SyntaxView.setSize(SyntaxView.java:812)
        at java.desktop/javax.swing.plaf.basic.BasicTextUI$RootView.setSize(BasicTextUI.java:1823)
        at java.desktop/javax.swing.plaf.basic.BasicTextUI.getPreferredSize(BasicTextUI.java:948)
        at java.desktop/javax.swing.plaf.basic.BasicTextAreaUI.getPreferredSize(BasicTextAreaUI.java:121)
        at java.desktop/javax.swing.JComponent.getPreferredSize(JComponent.java:1734)
        at java.desktop/javax.swing.JTextArea.getPreferredSize(JTextArea.java:623)
        at com.mucommander.viewer.text.TextLineNumbersPanel.lambda$documentChanged$0(TextLineNumbersPanel.java:314)
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
Reported in another project: https://github.com/mucommander/mucommander/issues/841 - of course something might be wrong in muC, but nevertheless `SyntaxView.calculateLongestLine` could check if `c` is not null, especially that `View.getContainer()` states that it may return null.

**Comment by bobbylight** [comment]
Interesting - even `javax.swing.text.PlainView`, which `SyntaxView` cribs off of, assumes `getContainer()` is never `null`. I think it *should* be the case that the conatiner is never `null` if that method is called, but perhaps that's not always the case for RSTA. Hopefully you can get more context here, e.g. does this occur before the component is realized or displayed? Thinking of "edge" cases here where things might not be fully initialized yet.

**Comment by bobbylight** [comment]
On second thought, do you have multiple threads doing initialization? I don't see how this exception is possible on the line indicated if all GUI work is done on the EDT:

* Before [SyntaxView.java#904](https://github.com/bobbylight/RSyntaxTextArea/blob/30a8237f8f33796eb718559ab9f23ee4865d2d37/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/SyntaxView.java#L904), we query for and use the result from `getContainer()`, so it must be non-`null`
* Thus in the next stack trace frame, [SyntaxView#103](https://github.com/bobbylight/RSyntaxTextArea/blob/30a8237f8f33796eb718559ab9f23ee4865d2d37/RSyntaxTextArea/src/main/java/org/fife/ui/rsyntaxtextarea/SyntaxView.java#L103), it should still be non-`null`

**Comment by pskowronek** [comment]
cannot reproduce in muC, closing
